version: "3.4"
services:
  civicrm:
    image: michaelmcandrew/civicrm:backdrop
    hostname: $PROJECT_NAME
    environment:
      - APACHE_RUN_USER=civicrm
      - PROJECT_NAME
      - BASE_URL
      - CIVICRM_DB_NAME
      - CIVICRM_DB_USER
      - CIVICRM_DB_PASS
      - CIVICRM_DB_HOST
      - CIVICRM_DB_PORT
      - BACKDROP_DB_NAME
      - BACKDROP_DB_USER
      - BACKDROP_DB_PASS
      - BACKDROP_DB_HOST
      - BACKDROP_DB_PORT
      - DEBUG=ON
      - SMTP_HOST
      - SMTP_MAILDOMAIN
    ports:
      - NNNN:80
    volumes:
      # - ./src:/var/www/html # uncomment for a mono-repo mounted from the host
      - files:/var/www/html/files
      - ./state:/state
      - ./.bash_history:/home/civicrm/.bash_history
    restart: always
  maildev:
    image: djfarrelly/maildev
    restart: always
    ports:
      - NNNN:80
volumes:
  files:
