version: "3.4"
services:
  civicrm:
    image: michaelmcandrew/civicrm:backdrop
    hostname: $PROJECT_NAME
    environment:
      - APACHE_RUN_USER=civicrm
      - PROJECT_NAME
      - BASE_URL
      - CIVICRM_DB_NAME
      - CIVICRM_DB_USER
      - CIVICRM_DB_PASS
      - CIVICRM_DB_HOST
      - CIVICRM_DB_PORT
      - BACKDROP_DB_NAME
      - BACKDROP_DB_USER
      - BACKDROP_DB_PASS
      - BACKDROP_DB_HOST
      - BACKDROP_DB_PORT
    ports:
      - NNNN:80
    volumes:
      - files:/var/www/html/files
      - ./state:/state
    restart: always
volumes:
  files:
